sudo: required
services:
  - docker

before_install:
  - docker build -t hugocordz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hugocordz/react-test npm test

after_success:
  - docker build -t hugocordz/multi-client ./client
  - docker build -t hugocordz/multi-nginx ./nginx
  - docker build -t hugocordz/multi-server ./server
  - docker build -t hugocordz/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push hugocordz/multi-client
  - docker push hugocordz/multi-nginx
  - docker push hugocordz/multi-server
  - docker push hugocordz/multi-worker

language: generic